# Generated by Django 2.1.1 on 2019-01-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.PositiveIntegerField(choices=[(0, 'Restaurant'), (1, 'Main Bar'), (2, 'Pool Bar'), (3, 'Store'), (4, 'Select Location')], default=4),
        ),
    ]
