# Generated by Django 2.1.1 on 2018-12-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['-id', '-arrival_date']},
        ),
    ]
