# Generated by Django 2.1.1 on 2018-11-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='sex',
            field=models.PositiveIntegerField(choices=[(0, 'Select'), (1, 'Female'), (2, 'Male')], default='Select '),
        ),
    ]
