# Generated by Django 2.1.1 on 2018-11-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20181130_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
