# Generated by Django 2.1.1 on 2018-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20181130_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='sex',
            field=models.PositiveIntegerField(choices=[(0, 'Select'), (1, 'Female'), (2, 'Male')], default=0),
        ),
    ]
