# Generated by Django 2.1.1 on 2018-12-08 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.PositiveIntegerField(choices=[(0, 'Select'), (1, 'Mr'), (2, 'Mrs')], default=0)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('usertype', models.CharField(choices=[('admin', 'Administrator'), ('frontdesk', 'Front Desk Officer'), ('laundry', 'Laundry Attendant'), ('store', 'Store Keeper'), ('bar', 'Bar Officer'), ('restaurant', 'Restaurant Personnel'), ('kitchen', 'Kitchen Officer')], default='front_desk', max_length=20, verbose_name='User Type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
